# Generated by Django 5.1.5 on 2025-01-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField()),
                ('custName', models.CharField(max_length=100)),
                ('custAddress', models.TextField()),
                ('custEmail', models.EmailField(max_length=30)),
                ('custPhoneNo', models.BigIntegerField()),
                ('custDob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eyewear',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDescription', models.TextField(blank=True, null=True)),
                ('stockQuantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EyewearDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('frameType', models.CharField(choices=[('Full Rim', 'Full Rim'), ('Half Rim', 'Half Rim'), ('Rimless', 'Rimless')], max_length=50)),
                ('lensType', models.CharField(choices=[('Single Vision', 'Single Vision'), ('Bifocal', 'Bifocal'), ('Progressive', 'Progressive'), ('Blue Light', 'Blue Light')], max_length=50)),
                ('warrantyPeriod', models.PositiveIntegerField()),
                ('eyewear', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Eyecraft.eyewear')),
            ],
        ),
    ]
