# Generated by Django 5.1.5 on 2025-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0003_alter_lensproduct_productimage_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
