# Generated by Django 5.1.5 on 2025-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0004_remove_cart_uid_alter_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensproduct',
            name='delete_details',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
