# Generated by Django 5.1.5 on 2025-01-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0005_lensproduct_delete_details_lensproduct_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
