# Generated by Django 5.1.5 on 2025-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0010_customerdetails_delete_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='user',
        ),
    ]
