# Generated by Django 5.1.5 on 2025-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0012_customerdetails_user_ordersdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensproduct',
            name='productImage_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='productImage_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='productImage_side',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='productImage_top',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
