# Generated by Django 5.1.6 on 2025-03-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0015_powerglasscategory_powerglassproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerglasscategory',
            name='parentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Eyecraft.powerglasscategory'),
        ),
    ]
