# Generated by Django 5.1.6 on 2025-03-03 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0017_remove_powerglassproduct_productcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerGlassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('categoryDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerGlassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('categoryDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComputerGlassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDesc', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productImage_main', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_side', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_back', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_top', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lensType', models.CharField(max_length=50)),
                ('frameMaterial', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_details', models.DateTimeField(blank=True, null=True)),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eyecraft.computerglasscategory')),
            ],
        ),
        migrations.CreateModel(
            name='PowerGlassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDesc', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productImage_main', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_side', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_back', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_top', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lensPower', models.CharField(max_length=50)),
                ('frameMaterial', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_details', models.DateTimeField(blank=True, null=True)),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eyecraft.powerglasscategory')),
            ],
        ),
    ]
