# Generated by Django 5.1.6 on 2025-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0018_computerglasscategory_powerglasscategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensproduct',
            name='BrandName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
