# Generated by Django 5.1.6 on 2025-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0019_lensproduct_brandname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerglassproduct',
            name='frameMaterial',
        ),
        migrations.RemoveField(
            model_name='powerglassproduct',
            name='lensPower',
        ),
        migrations.AddField(
            model_name='powerglassproduct',
            name='BrandName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
