# Generated by Django 5.1.6 on 2025-03-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0020_remove_powerglassproduct_framematerial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='Eyecraft.powerglasscategory'),
        ),
    ]
