# Generated by Django 5.1.6 on 2025-03-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0021_alter_cart_pid'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.AddField(
            model_name='cart',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cart',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
