# Generated by Django 5.1.6 on 2025-03-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0022_remove_cart_pid_cart_content_type_cart_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eyecraft.lensproduct'),
        ),
    ]
