# Generated by Django 5.1.6 on 2025-03-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0025_cart_pid2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerglassproduct',
            name='frameMaterial',
        ),
        migrations.RemoveField(
            model_name='computerglassproduct',
            name='lensType',
        ),
    ]
