# Generated by Django 5.1.6 on 2025-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0026_remove_computerglassproduct_framematerial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenscategory',
            name='categoryName',
            field=models.CharField(choices=[('EYE_GLASSES', 'Eye Glasses'), ('POWER_GLASSES', 'Power Glasses'), ('SUN_GLASSES', 'Sun Glasses'), ('COMPUTER_GLASSES', 'Computer Glasses'), ('CONTACT_LENSES', 'Contact Lenses'), ('ACCESSORIES', 'Accessories')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lensproduct',
            name='productRating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
