# Generated by Django 5.1.6 on 2025-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0027_alter_lenscategory_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerglassproduct',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='powerglassproduct',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pid2',
        ),
        migrations.RemoveField(
            model_name='sunglassproduct',
            name='productCategory',
        ),
        migrations.AlterField(
            model_name='lensproduct',
            name='productCategory',
            field=models.CharField(choices=[('EYE_GLASSES', 'Eye Glasses'), ('POWER_GLASSES', 'Power Glasses'), ('SUN_GLASSES', 'Sun Glasses'), ('COMPUTER_GLASSES', 'Computer Glasses'), ('CONTACT_LENSES', 'Contact Lenses'), ('ACCESSORIES', 'Accessories')], default='EYE_GLASSES', max_length=50),
        ),
        migrations.DeleteModel(
            name='ComputerGlassCategory',
        ),
        migrations.DeleteModel(
            name='ComputerGlassProduct',
        ),
        migrations.DeleteModel(
            name='PowerGlassCategory',
        ),
        migrations.DeleteModel(
            name='PowerGlassProduct',
        ),
        migrations.DeleteModel(
            name='SunglassCategory',
        ),
        migrations.DeleteModel(
            name='SunglassProduct',
        ),
    ]
