# Generated by Django 5.1.6 on 2025-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0028_remove_computerglassproduct_productcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LensCategory',
        ),
        migrations.AddField(
            model_name='lensproduct',
            name='productRimType',
            field=models.CharField(choices=[('RIMMED', 'Rimmed'), ('SEMI_RIMMED', 'Semi-Rimmed'), ('RIMLESS', 'Rimless')], default='RIMMED', max_length=20),
        ),
    ]
