# Generated by Django 5.1.6 on 2025-03-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0031_ordersdetail_payment_status_delete_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordersdetail',
        ),
    ]
