# Generated by Django 5.1.6 on 2025-03-26 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0037_remove_orderitem_price_alter_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='custcontact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='custname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
