# Generated by Django 5.1.6 on 2025-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0038_alter_customerdetails_custcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Bausch & Lomb', 'Bausch & Lomb'), ('Acuvue', 'Acuvue'), ('CooperVision', 'CooperVision'), ('Alcon', 'Alcon')], default='Bausch & Lomb', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='contact_lenses/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
