# Generated by Django 5.1.6 on 2025-03-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0039_contactlens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactLens',
        ),
    ]
