# Generated by Django 5.1.6 on 2025-03-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0040_delete_contactlens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Eyecraft.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Bausch & Lomb', 'Bausch & Lomb'), ('Acuvue', 'Acuvue'), ('CooperVision', 'CooperVision'), ('Alcon', 'Alcon')], default='Bausch & Lomb', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productImage_main', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_side', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_back', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productImage_top', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Eyecraft.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Eyecraft.subcategory')),
            ],
        ),
    ]
