# Generated by Django 5.1.6 on 2025-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0043_alter_lensproduct_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
