# Generated by Django 5.1.6 on 2025-04-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eyecraft', '0044_customer_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='forget_password_token',
        ),
    ]
